# metadata specialised for each experiment
core:
  project_name: test_nn_template
  storage_dir: ${oc.env:PROJECT_ROOT}/storage
  version: 0.0.1
  tags: ["develop"]

defaults:
  - hydra: default
  - data: default
  - train: default
  - optim: default
  - model: default
  - _self_ # as last argument to allow the override of parameters via this main config
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib
